version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/clear_cache.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_services.sh
      timeout: 300
      runas: root
